import {chromium} from '@playwright/test';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5179/?test&review');
await page.getByRole('button',{name:'Review lettuce',exact:true}).click();
await page.screenshot({path:'artifacts/lettuce-before.png'});
await page.getByRole('button',{name:'Toggle E',exact:true}).click();await page.getByRole('button',{name:'Step 0.2 s',exact:true}).click();
await page.screenshot({path:'artifacts/lettuce-bite.png'});
console.log('bite',await page.evaluate(()=>window.__sluger.state()));
await page.getByRole('button',{name:'Review beer',exact:true}).click();await page.getByRole('button',{name:'Step 0.2 s',exact:true}).click();
await page.screenshot({path:'artifacts/beer-window.png'});
await page.getByRole('button',{name:'Toggle retreat',exact:true}).click();await page.evaluate(()=>window.__sluger.step(1.5));
await page.screenshot({path:'artifacts/beer-recovered.png'});
console.log('escape',await page.evaluate(()=>window.__sluger.state()));
await page.getByRole('button',{name:'Review home',exact:true}).click();await page.evaluate(()=>window.__sluger.step(.8));
await page.screenshot({path:'artifacts/home-entering.png'});await page.evaluate(()=>window.__sluger.step(3));
await page.screenshot({path:'artifacts/home-result.png'});
await page.setViewportSize({width:390,height:700});await page.screenshot({path:'artifacts/home-mobile.png'});
console.log('errors',errors);await browser.close();
