import {chromium} from '@playwright/test';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5179/?test&review');
await page.getByRole('button',{name:'Into the garden'}).click();
await page.evaluate(()=>{window.__sluger.place(-1.6,6.6);window.__sluger.gardener(-10,-10,Math.PI);window.__sluger.view([.3,1.8,8.5],[-2.8,.05,4.9]);window.__sluger.step(.1);});
await page.screenshot({path:'artifacts/partner-trail.png'});
await page.getByRole('button',{name:'Review companion',exact:true}).click();
await page.getByRole('button',{name:'Toggle E',exact:true}).click();await page.evaluate(()=>window.__sluger.step(1));
await page.screenshot({path:'artifacts/partner-meeting.png'});
await page.evaluate(()=>window.__sluger.step(1.2));
await page.screenshot({path:'artifacts/partner-met.png'});
await page.getByRole('button',{name:'Review nest',exact:true}).click();await page.evaluate(()=>window.__sluger.step(.1));
await page.screenshot({path:'artifacts/partner-nest-choice.png'});
await page.getByRole('button',{name:'Toggle E',exact:true}).click();await page.evaluate(()=>window.__sluger.step(4.5));
await page.screenshot({path:'artifacts/partner-result.png'});
await page.getByRole('button',{name:'One more evening'}).click();
await page.evaluate(()=>{window.__sluger.view([1,1,8.4],[0,.08,10.1]);});
await page.screenshot({path:'artifacts/partner-eggs.png'});
await page.setViewportSize({width:390,height:700});await page.reload();
await page.evaluate(()=>document.getElementById('review-controls').hidden=true);
await page.screenshot({path:'artifacts/partner-mobile-intro.png'});
await page.evaluate(()=>document.getElementById('review-controls').hidden=false);
await page.getByRole('button',{name:'Review nest',exact:true}).click();await page.evaluate(()=>{window.__sluger.stats(30,100);window.__sluger.step(.1);});
await page.evaluate(()=>document.getElementById('review-controls').hidden=true);
await page.screenshot({path:'artifacts/partner-mobile-dry.png'});
console.log(JSON.stringify({errors,state:await page.evaluate(()=>window.__sluger.state())}));await browser.close();
